import {ProductType} from "./productType";


export const products:ProductType[]=[
    {"id":1,"name":"Mobile","img":"../../../assets/mobile.jpg","description":["product description .. Redmi Note 10 Pro description"," Redmi Note 10 Pro(Dark Night, 6GB RAM, 128GB Storage) -120hz Super Amoled Display|64MPwith 5mp Super Tele-Macro | 33W Charger Included"],"price":199,"count":0 , "totalPrice":0 ,"category":"electronics"},
    {"id":2,"name":"Laptop","img":"../../../assets/laptop.jpg","description":["product description .. Lenovo IdeaPad  description","Lenovo IdeaPad Slim 3 11th Gen Intel Core i5 15.6 inches FHD Thin & Light Laptop (8GB/512GB SSD/Windows 11/Office 2021/2Yr Warranty/Backlit/3months Xbox Game Pass/Arctic Grey/1.65Kg), 82H802FHIN"],"price":1299,"count":0, "totalPrice":0,"category":"electronics"},
    {"id":3,"name":"Headset","img":"../../../assets/headset.jpg","description":["product description .. boAt headset description","boAt Rockerz 370 Bluetooth Wireless On Ear Headphone with Mic (Fiery Red) "],"price":149,"count":0, "totalPrice":0 ,"category":"electronics"},
    {"id":4,"name":"Powerbank","img":"../../../assets/powerbank.jpg","description":["product description .. PTron powerbank description","PTron 10000 mAh lithium_polymer Dynamo Pro Power Bank with 18 Watt Fast Charging, Black "],"price":99,"count":0, "totalPrice":0 ,"category":"accessoriess"},
    {"id":5,"name":"Gamesystem","img":"../../../assets/gamesystem.jpg","description":["product description .. PS5 gamesystem description","New World PS5 Vertical Stand for PS5 Digital Edition/Ultra HD Console with Cooling Fan, Controller Charging Station and 15 Game Cards Slots and Headset Stand"],"price":799,"count":0, "totalPrice":0 ,"category":"electronics"},
    {"id":6,"name":"Speaker","img":"../../../assets/speaker.jpg","description":["product description .. Bluetooth Speaker description","Clavier Pluto Portable Bluetooth Speaker, Bluetooth 5.0 Wireless Speakers with HD Sound and Rich Bass, LED Flashing Light, Built-in Mic for iPhone & Android, "],"price":499,"count":0, "totalPrice":0 ,"category":"electronics"},
    {"id":7,"name":"Bag","img":"../../../assets/bag.jpg","description":["product description .. Bag description","Gear Superior Backpack Orange-Black Backpack (BKPSPRIOR0601) "],"price":499,"count":0, "totalPrice":0 ,"category":"accessories"},
    {"id":8,"name":"Watch","img":"../../../assets/watch.jpg","description":["product description .. Watch description","Fossil Chronograph Men's Watch (Black Dial Black Colored Strap)"],"price":499,"count":0, "totalPrice":0 ,"category":"accessories"},
    {"id":9,"name":"Toolkit","img":"../../../assets/toolkit.jpg","description":["product description .. Toolkit description","Flexzion Tool Set Box - Hand Tool Kit & Accessories For General Household DIY Home Repair with Plastic Toolbox Storage Organizer Case - Homeowner's Tool Kit (Orange & Black)"],"price":499,"count":0, "totalPrice":0 ,"category":"accessories"},
]

//https://m.media-amazon.com/images/I/91xzHw+Ja-L._UX679_.jpg  
export const usersAr:any=[{username:"admin",email:"admin@pettikadai.com",password:"admin13",confirmpassword:"admin13" , address:"Pettikadai , thiru vi ka Industrial Estate, Guindy-600058",orders:[]}];